// Vortex / GOS3 v2.4 — Rhino CAD Connector
// Rule: mexeu → testa → valida → publica.

import { RhinoExecutor, RhinoExecutionResult, RhinoSceneProposal, RhinoValidationResult } from "./types";

const number = (value: number, field: string): string => {
  if (!Number.isFinite(value)) throw new Error(`${field} must be finite`);
  return String(value);
};

const point = (p: [number, number, number], field: string): string =>
  `(${number(p[0], `${field}.x`)}, ${number(p[1], `${field}.y`)}, ${number(p[2], `${field}.z`)})`;

export function validateProposal(proposal: RhinoSceneProposal): RhinoValidationResult {
  const errors: string[] = [];
  if (proposal.protocol_version !== "vortex-rhino/v1") errors.push("unsupported protocol_version");
  if (!Array.isArray(proposal.operations) || proposal.operations.length === 0) errors.push("operations must not be empty");
  const names = new Set<string>();
  proposal.operations.forEach((op, index) => {
    if ("name" in op && op.name) {
      if (!/^[A-Za-z0-9_.-]+$/.test(op.name)) errors.push(`operations[${index}].name contains invalid characters`);
      if (names.has(op.name)) errors.push(`duplicate object name: ${op.name}`);
      names.add(op.name);
    }
    const positive = (v: number, field: string) => {
      if (!Number.isFinite(v) || v <= 0) errors.push(`operations[${index}].${field} must be > 0`);
    };
    try {
      if (op.type === "box") op.size.forEach((v, i) => positive(v, `size[${i}]`));
      if (op.type === "cylinder") { positive(op.radius, "radius"); positive(op.height, "height"); }
      if (op.type === "sphere") positive(op.radius, "radius");
      if (op.type === "hole") { positive(op.radius, "radius"); positive(op.depth, "depth"); }
      if (op.type === "fillet") positive(op.radius, "radius");
      if (op.type === "export" && !/^([A-Za-z]:[\\/]|\/|\.\/|\.\.\/)/.test(op.path)) errors.push(`operations[${index}].path must be an explicit filesystem path`);
    } catch (error) {
      errors.push(`operations[${index}] contains invalid numeric data: ${String(error)}`);
    }
  });
  return { valid: errors.length === 0, errors };
}

export function renderPython(proposal: RhinoSceneProposal): string {
  const validation = validateProposal(proposal);
  if (!validation.valid) throw new Error(`Invalid Rhino proposal: ${validation.errors.join("; ")}`);
  const lines = [
    "# Generated by Vortex Rhino Connector — review before execution",
    "import rhinoscriptsyntax as rs",
    `rs.UnitSystem(rs.unitSystem.${proposal.units}) if hasattr(rs.unitSystem, '${proposal.units}') else None`,
    "_vortex_objects = {}"
  ];
  for (const op of proposal.operations) {
    const name = "name" in op && op.name ? op.name : undefined;
    if (op.type === "box") {
      lines.push(`_id = rs.AddBox([${point(op.origin, "origin")}, (${number(op.size[0], "size.x")}, ${number(op.size[1], "size.y")}, ${number(op.size[2], "size.z")})])`);
    } else if (op.type === "cylinder") {
      lines.push(`_id = rs.AddCylinder(${point(op.base, "base")}, ${number(op.height, "height")}, ${number(op.radius, "radius")})`);
    } else if (op.type === "sphere") {
      lines.push(`_id = rs.AddSphere(${point(op.center, "center")}, ${number(op.radius, "radius")})`);
    } else if (op.type === "hole") {
      lines.push(`_id = rs.AddCylinder(${point(op.center, "center")}, ${number(op.depth, "depth")}, ${number(op.radius, "radius")})`);
    } else if (op.type === "fillet") {
      lines.push(`_id = rs.Command("_FilletEdge Radius=${number(op.radius, "radius")} Enter Enter", False)`);
    } else if (op.type === "boolean_difference") {
      lines.push(`_target = _vortex_objects.get(${JSON.stringify(op.target)}); _cutter = _vortex_objects.get(${JSON.stringify(op.cutter)}); rs.BooleanDifference(_target, _cutter) if _target and _cutter else None`);
    } else if (op.type === "export") {
      lines.push(`rs.Command("_-Export ${JSON.stringify(op.path)} _Enter", False)`);
    }
    if (name) lines.push(`_vortex_objects[${JSON.stringify(name)}] = _id`);
  }
  lines.push("print('VORTEX_RHINO_EXECUTION_READY')");
  return lines.join("\n");
}

export class RhinoAdapter {
  public constructor(private readonly executor: RhinoExecutor) {}

  public async execute(proposal: RhinoSceneProposal): Promise<RhinoExecutionResult> {
    const validation = validateProposal(proposal);
    if (!validation.valid) throw new Error(`Invalid Rhino proposal: ${validation.errors.join("; ")}`);
    return this.executor.execute(renderPython(proposal));
  }
}
