// Vortex / GOS3 v2.4 — Rhino CAD Connector
// Rule: mexeu → testa → valida → publica.

import { RhinoExecutor, RhinoExecutionResult, RhinoSceneProposal, RhinoValidationResult } from "./types";

const number = (value: number, field: string): string => {
  if (!Number.isFinite(value)) throw new Error(`${field} must be finite`);
  return String(value);
};

const point = (p: [number, number, number], field: string): string =>
  `(${number(p[0], `${field}.x`)}, ${number(p[1], `${field}.y`)}, ${number(p[2], `${field}.z`)})`;

export function validateProposal(proposal: RhinoSceneProposal): RhinoValidationResult {
  const errors: string[] = [];
  if (proposal.protocol_version !== "vortex-rhino/v1") errors.push("unsupported protocol_version");
  if (!Array.isArray(proposal.operations) || proposal.operations.length === 0) errors.push("operations must not be empty");
  const names = new Set<string>();
  proposal.operations.forEach((op, index) => {
    if ("name" in op && op.name) {
      if (!/^[A-Za-z0-9_.-]+$/.test(op.name)) errors.push(`operations[${index}].name contains invalid characters`);
      if (names.has(op.name)) errors.push(`duplicate object name: ${op.name}`);
      names.add(op.name);
    }
    const positive = (v: number, field: string) => {
      if (!Number.isFinite(v) || v <= 0) errors.push(`operations[${index}].${field} must be > 0`);
    };
    if (op.type === "box") op.size.forEach((v, i) => positive(v, `size[${i}]`));
    if (op.type === "cylinder") { positive(op.radius, "radius"); positive(op.height, "height"); }
    if (op.type === "sphere") positive(op.radius, "radius");
    if (op.type === "hole") { positive(op.radius, "radius"); positive(op.depth, "depth"); }
    if (op.type === "fillet") positive(op.radius, "radius");
    if (op.type === "export" && !/^([A-Za-z]:[\\/]|\/|\.\/|\.\.\/)/.test(op.path)) errors.push(`operations[${index}].path must be an explicit filesystem path`);
  });
  return { valid: errors.length === 0, errors };
}

export function renderPython(proposal: RhinoSceneProposal): string {
  const validation = validateProposal(proposal);
  if (!validation.valid) throw new Error(`Invalid Rhino proposal: ${validation.errors.join("; ")}`);
  const lines = [
    "# Generated by Vortex Rhino Connector — review before execution",
    "import rhinoscriptsyntax as rs",
    "_vortex_objects = {}",
    `# Requested units: ${proposal.units}`
  ];
  for (const op of proposal.operations) {
    const name = "name" in op && op.name ? op.name : undefined;
    if (op.type === "box") {
      const [x, y, z] = op.origin;
      const [sx, sy, sz] = op.size;
      const pts: [number, number, number][] = [
        [x, y, z], [x + sx, y, z], [x + sx, y + sy, z], [x, y + sy, z],
        [x, y, z + sz], [x + sx, y, z + sz], [x + sx, y + sy, z + sz], [x, y + sy, z + sz]
      ];
      lines.push(`_id = rs.AddBox([${pts.map((p, i) => point(p, `box[${i}]`)).join(", ")}])`);
    } else if (op.type === "cylinder") {
      lines.push(`_id = rs.AddCylinder(${point(op.base, "base")}, ${number(op.height, "height")}, ${number(op.radius, "radius")})`);
    } else if (op.type === "sphere") {
      lines.push(`_id = rs.AddSphere(${point(op.center, "center")}, ${number(op.radius, "radius")})`);
    } else if (op.type === "hole") {
      lines.push(`# Hole cutter: center=${point(op.center, "center")}, depth=${number(op.depth, "depth")}, radius=${number(op.radius, "radius")}`);
      lines.push(`_id = rs.AddCylinder(${point(op.center, "center")}, ${number(op.depth, "depth")}, ${number(op.radius, "radius")})`);
    } else if (op.type === "fillet") {
      lines.push(`# Fillet requested: radius=${number(op.radius, "radius")}; selection must be supplied by the host`);
      lines.push("_id = None");
    } else if (op.type === "boolean_difference") {
      lines.push(`_target = _vortex_objects.get(${JSON.stringify(op.target)}); _cutter = _vortex_objects.get(${JSON.stringify(op.cutter)}); _id = rs.BooleanDifference(_target, _cutter) if _target and _cutter else None`);
    } else if (op.type === "export") {
      const escaped = op.path.replace(/([\\\"])/g, "\\$1");
      lines.push(`rs.Command("_-Export ${escaped} _Enter", False)`);
      lines.push(`_id = None`);
    }
    if (name) lines.push(`_vortex_objects[${JSON.stringify(name)}] = _id`);
  }
  lines.push("print('VORTEX_RHINO_EXECUTION_READY')");
  return lines.join("\n");
}

export class RhinoAdapter {
  public constructor(private readonly executor: RhinoExecutor) {}

  public async execute(proposal: RhinoSceneProposal): Promise<RhinoExecutionResult> {
    const validation = validateProposal(proposal);
    if (!validation.valid) throw new Error(`Invalid Rhino proposal: ${validation.errors.join("; ")}`);
    return this.executor.execute(renderPython(proposal));
  }
}
